export const skillsData = [
    'HTML',
    'CSS',
    'Javascript',
     'Kubernetes',
    'React',
    'Linux',
    'MongoDB',
    'MySQL',
    'Git',
    'AWS',
    'Django',
    'Docker',
    'ChakraUI',
    'Tailwind',
    'Redux',
  ]